export default [
  {
    type: 'constructor',
    stateMutability: 'nonpayable',
    payable: false,
    inputs: [
      { type: 'address', name: '_factoryProxy', internalType: 'address' },
      { type: 'address', name: '_WNRG', internalType: 'address' },
      { type: 'address', name: '_sporkProxy', internalType: 'address' },
      { type: 'address', name: '_proxy', internalType: 'address' },
    ],
  },
  { type: 'fallback', stateMutability: 'payable', payable: true },
  {
    type: 'function',
    stateMutability: 'view',
    payable: false,
    outputs: [
      {
        type: 'address',
        name: '',
        internalType: 'contract EnergiswapRouterStorage',
      },
    ],
    name: '_storage',
    inputs: [],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    payable: false,
    outputs: [
      { type: 'uint256', name: 'amountA', internalType: 'uint256' },
      { type: 'uint256', name: 'amountB', internalType: 'uint256' },
      { type: 'uint256', name: 'liquidity', internalType: 'uint256' },
    ],
    name: 'addLiquidity',
    inputs: [
      { type: 'address', name: 'tokenA', internalType: 'address' },
      { type: 'address', name: 'tokenB', internalType: 'address' },
      { type: 'uint256', name: 'amountADesired', internalType: 'uint256' },
      { type: 'uint256', name: 'amountBDesired', internalType: 'uint256' },
      { type: 'uint256', name: 'amountAMin', internalType: 'uint256' },
      { type: 'uint256', name: 'amountBMin', internalType: 'uint256' },
      { type: 'address', name: 'to', internalType: 'address' },
      { type: 'uint256', name: 'deadline', internalType: 'uint256' },
    ],
    constant: false,
  },
  {
    type: 'function',
    stateMutability: 'payable',
    payable: true,
    outputs: [
      { type: 'uint256', name: 'amountToken', internalType: 'uint256' },
      { type: 'uint256', name: 'amountNRG', internalType: 'uint256' },
      { type: 'uint256', name: 'liquidity', internalType: 'uint256' },
    ],
    name: 'addLiquidityNRG',
    inputs: [
      { type: 'address', name: 'token', internalType: 'address' },
      { type: 'uint256', name: 'amountTokenDesired', internalType: 'uint256' },
      { type: 'uint256', name: 'amountTokenMin', internalType: 'uint256' },
      { type: 'uint256', name: 'amountNRGMin', internalType: 'uint256' },
      { type: 'address', name: 'to', internalType: 'address' },
      { type: 'uint256', name: 'deadline', internalType: 'uint256' },
    ],
    constant: false,
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    payable: false,
    outputs: [],
    name: 'destroy',
    inputs: [{ type: 'address', name: '_newImpl', internalType: 'address' }],
    constant: false,
  },
  {
    type: 'function',
    stateMutability: 'pure',
    payable: false,
    outputs: [{ type: 'uint256', name: 'amountIn', internalType: 'uint256' }],
    name: 'getAmountIn',
    inputs: [
      { type: 'uint256', name: 'amountOut', internalType: 'uint256' },
      { type: 'uint256', name: 'reserveIn', internalType: 'uint256' },
      { type: 'uint256', name: 'reserveOut', internalType: 'uint256' },
    ],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'pure',
    payable: false,
    outputs: [{ type: 'uint256', name: 'amountOut', internalType: 'uint256' }],
    name: 'getAmountOut',
    inputs: [
      { type: 'uint256', name: 'amountIn', internalType: 'uint256' },
      { type: 'uint256', name: 'reserveIn', internalType: 'uint256' },
      { type: 'uint256', name: 'reserveOut', internalType: 'uint256' },
    ],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'view',
    payable: false,
    outputs: [
      { type: 'uint256[]', name: 'amounts', internalType: 'uint256[]' },
    ],
    name: 'getAmountsIn',
    inputs: [
      { type: 'uint256', name: 'amountOut', internalType: 'uint256' },
      { type: 'address[]', name: 'path', internalType: 'address[]' },
    ],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'view',
    payable: false,
    outputs: [
      { type: 'uint256[]', name: 'amounts', internalType: 'uint256[]' },
    ],
    name: 'getAmountsOut',
    inputs: [
      { type: 'uint256', name: 'amountIn', internalType: 'uint256' },
      { type: 'address[]', name: 'path', internalType: 'address[]' },
    ],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    payable: false,
    outputs: [],
    name: 'migrate',
    inputs: [{ type: 'address', name: '_oldImpl', internalType: 'address' }],
    constant: false,
  },
  {
    type: 'function',
    stateMutability: 'view',
    payable: false,
    outputs: [{ type: 'address', name: '', internalType: 'address' }],
    name: 'proxy',
    inputs: [],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'pure',
    payable: false,
    outputs: [{ type: 'uint256', name: 'amountB', internalType: 'uint256' }],
    name: 'quote',
    inputs: [
      { type: 'uint256', name: 'amountA', internalType: 'uint256' },
      { type: 'uint256', name: 'reserveA', internalType: 'uint256' },
      { type: 'uint256', name: 'reserveB', internalType: 'uint256' },
    ],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    payable: false,
    outputs: [
      { type: 'uint256', name: 'amountA', internalType: 'uint256' },
      { type: 'uint256', name: 'amountB', internalType: 'uint256' },
    ],
    name: 'removeLiquidity',
    inputs: [
      { type: 'address', name: 'tokenA', internalType: 'address' },
      { type: 'address', name: 'tokenB', internalType: 'address' },
      { type: 'uint256', name: 'liquidity', internalType: 'uint256' },
      { type: 'uint256', name: 'amountAMin', internalType: 'uint256' },
      { type: 'uint256', name: 'amountBMin', internalType: 'uint256' },
      { type: 'address', name: 'to', internalType: 'address' },
      { type: 'uint256', name: 'deadline', internalType: 'uint256' },
    ],
    constant: false,
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    payable: false,
    outputs: [
      { type: 'uint256', name: 'amountToken', internalType: 'uint256' },
      { type: 'uint256', name: 'amountNRG', internalType: 'uint256' },
    ],
    name: 'removeLiquidityNRG',
    inputs: [
      { type: 'address', name: 'token', internalType: 'address' },
      { type: 'uint256', name: 'liquidity', internalType: 'uint256' },
      { type: 'uint256', name: 'amountTokenMin', internalType: 'uint256' },
      { type: 'uint256', name: 'amountNRGMin', internalType: 'uint256' },
      { type: 'address', name: 'to', internalType: 'address' },
      { type: 'uint256', name: 'deadline', internalType: 'uint256' },
    ],
    constant: false,
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    payable: false,
    outputs: [{ type: 'uint256', name: 'amountNRG', internalType: 'uint256' }],
    name: 'removeLiquidityNRGSupportingFeeOnTransferTokens',
    inputs: [
      { type: 'address', name: 'token', internalType: 'address' },
      { type: 'uint256', name: 'liquidity', internalType: 'uint256' },
      { type: 'uint256', name: 'amountTokenMin', internalType: 'uint256' },
      { type: 'uint256', name: 'amountNRGMin', internalType: 'uint256' },
      { type: 'address', name: 'to', internalType: 'address' },
      { type: 'uint256', name: 'deadline', internalType: 'uint256' },
    ],
    constant: false,
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    payable: false,
    outputs: [
      { type: 'uint256', name: 'amountToken', internalType: 'uint256' },
      { type: 'uint256', name: 'amountNRG', internalType: 'uint256' },
    ],
    name: 'removeLiquidityNRGWithPermit',
    inputs: [
      { type: 'address', name: 'token', internalType: 'address' },
      { type: 'uint256', name: 'liquidity', internalType: 'uint256' },
      { type: 'uint256', name: 'amountTokenMin', internalType: 'uint256' },
      { type: 'uint256', name: 'amountNRGMin', internalType: 'uint256' },
      { type: 'address', name: 'to', internalType: 'address' },
      { type: 'uint256', name: 'deadline', internalType: 'uint256' },
      { type: 'bool', name: 'approveMax', internalType: 'bool' },
      { type: 'uint8', name: 'v', internalType: 'uint8' },
      { type: 'bytes32', name: 'r', internalType: 'bytes32' },
      { type: 'bytes32', name: 's', internalType: 'bytes32' },
    ],
    constant: false,
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    payable: false,
    outputs: [{ type: 'uint256', name: 'amountNRG', internalType: 'uint256' }],
    name: 'removeLiquidityNRGWithPermitSupportingFeeOnTransferTokens',
    inputs: [
      { type: 'address', name: 'token', internalType: 'address' },
      { type: 'uint256', name: 'liquidity', internalType: 'uint256' },
      { type: 'uint256', name: 'amountTokenMin', internalType: 'uint256' },
      { type: 'uint256', name: 'amountNRGMin', internalType: 'uint256' },
      { type: 'address', name: 'to', internalType: 'address' },
      { type: 'uint256', name: 'deadline', internalType: 'uint256' },
      { type: 'bool', name: 'approveMax', internalType: 'bool' },
      { type: 'uint8', name: 'v', internalType: 'uint8' },
      { type: 'bytes32', name: 'r', internalType: 'bytes32' },
      { type: 'bytes32', name: 's', internalType: 'bytes32' },
    ],
    constant: false,
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    payable: false,
    outputs: [
      { type: 'uint256', name: 'amountA', internalType: 'uint256' },
      { type: 'uint256', name: 'amountB', internalType: 'uint256' },
    ],
    name: 'removeLiquidityWithPermit',
    inputs: [
      { type: 'address', name: 'tokenA', internalType: 'address' },
      { type: 'address', name: 'tokenB', internalType: 'address' },
      { type: 'uint256', name: 'liquidity', internalType: 'uint256' },
      { type: 'uint256', name: 'amountAMin', internalType: 'uint256' },
      { type: 'uint256', name: 'amountBMin', internalType: 'uint256' },
      { type: 'address', name: 'to', internalType: 'address' },
      { type: 'uint256', name: 'deadline', internalType: 'uint256' },
      { type: 'bool', name: 'approveMax', internalType: 'bool' },
      { type: 'uint8', name: 'v', internalType: 'uint8' },
      { type: 'bytes32', name: 'r', internalType: 'bytes32' },
      { type: 'bytes32', name: 's', internalType: 'bytes32' },
    ],
    constant: false,
  },
  {
    type: 'function',
    stateMutability: 'payable',
    payable: true,
    outputs: [
      { type: 'uint256[]', name: 'amounts', internalType: 'uint256[]' },
    ],
    name: 'swapExactNRGForTokens',
    inputs: [
      { type: 'uint256', name: 'amountOutMin', internalType: 'uint256' },
      { type: 'address[]', name: 'path', internalType: 'address[]' },
      { type: 'address', name: 'to', internalType: 'address' },
      { type: 'uint256', name: 'deadline', internalType: 'uint256' },
    ],
    constant: false,
  },
  {
    type: 'function',
    stateMutability: 'payable',
    payable: true,
    outputs: [],
    name: 'swapExactNRGForTokensSupportingFeeOnTransferTokens',
    inputs: [
      { type: 'uint256', name: 'amountOutMin', internalType: 'uint256' },
      { type: 'address[]', name: 'path', internalType: 'address[]' },
      { type: 'address', name: 'to', internalType: 'address' },
      { type: 'uint256', name: 'deadline', internalType: 'uint256' },
    ],
    constant: false,
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    payable: false,
    outputs: [
      { type: 'uint256[]', name: 'amounts', internalType: 'uint256[]' },
    ],
    name: 'swapExactTokensForNRG',
    inputs: [
      { type: 'uint256', name: 'amountIn', internalType: 'uint256' },
      { type: 'uint256', name: 'amountOutMin', internalType: 'uint256' },
      { type: 'address[]', name: 'path', internalType: 'address[]' },
      { type: 'address', name: 'to', internalType: 'address' },
      { type: 'uint256', name: 'deadline', internalType: 'uint256' },
    ],
    constant: false,
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    payable: false,
    outputs: [],
    name: 'swapExactTokensForNRGSupportingFeeOnTransferTokens',
    inputs: [
      { type: 'uint256', name: 'amountIn', internalType: 'uint256' },
      { type: 'uint256', name: 'amountOutMin', internalType: 'uint256' },
      { type: 'address[]', name: 'path', internalType: 'address[]' },
      { type: 'address', name: 'to', internalType: 'address' },
      { type: 'uint256', name: 'deadline', internalType: 'uint256' },
    ],
    constant: false,
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    payable: false,
    outputs: [
      { type: 'uint256[]', name: 'amounts', internalType: 'uint256[]' },
    ],
    name: 'swapExactTokensForTokens',
    inputs: [
      { type: 'uint256', name: 'amountIn', internalType: 'uint256' },
      { type: 'uint256', name: 'amountOutMin', internalType: 'uint256' },
      { type: 'address[]', name: 'path', internalType: 'address[]' },
      { type: 'address', name: 'to', internalType: 'address' },
      { type: 'uint256', name: 'deadline', internalType: 'uint256' },
    ],
    constant: false,
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    payable: false,
    outputs: [],
    name: 'swapExactTokensForTokensSupportingFeeOnTransferTokens',
    inputs: [
      { type: 'uint256', name: 'amountIn', internalType: 'uint256' },
      { type: 'uint256', name: 'amountOutMin', internalType: 'uint256' },
      { type: 'address[]', name: 'path', internalType: 'address[]' },
      { type: 'address', name: 'to', internalType: 'address' },
      { type: 'uint256', name: 'deadline', internalType: 'uint256' },
    ],
    constant: false,
  },
  {
    type: 'function',
    stateMutability: 'payable',
    payable: true,
    outputs: [
      { type: 'uint256[]', name: 'amounts', internalType: 'uint256[]' },
    ],
    name: 'swapNRGForExactTokens',
    inputs: [
      { type: 'uint256', name: 'amountOut', internalType: 'uint256' },
      { type: 'address[]', name: 'path', internalType: 'address[]' },
      { type: 'address', name: 'to', internalType: 'address' },
      { type: 'uint256', name: 'deadline', internalType: 'uint256' },
    ],
    constant: false,
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    payable: false,
    outputs: [
      { type: 'uint256[]', name: 'amounts', internalType: 'uint256[]' },
    ],
    name: 'swapTokensForExactNRG',
    inputs: [
      { type: 'uint256', name: 'amountOut', internalType: 'uint256' },
      { type: 'uint256', name: 'amountInMax', internalType: 'uint256' },
      { type: 'address[]', name: 'path', internalType: 'address[]' },
      { type: 'address', name: 'to', internalType: 'address' },
      { type: 'uint256', name: 'deadline', internalType: 'uint256' },
    ],
    constant: false,
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    payable: false,
    outputs: [
      { type: 'uint256[]', name: 'amounts', internalType: 'uint256[]' },
    ],
    name: 'swapTokensForExactTokens',
    inputs: [
      { type: 'uint256', name: 'amountOut', internalType: 'uint256' },
      { type: 'uint256', name: 'amountInMax', internalType: 'uint256' },
      { type: 'address[]', name: 'path', internalType: 'address[]' },
      { type: 'address', name: 'to', internalType: 'address' },
      { type: 'uint256', name: 'deadline', internalType: 'uint256' },
    ],
    constant: false,
  },
]
